---
# ydbd configuration

- name: Add the configuration backup script
  template: src=backup_config.j2 dest={{ ydb_dir }}/home/backup_config.sh mode=755

- name: Add the configuration file updater script
  template: src=update_config_file.j2 dest={{ ydb_dir }}/home/update_config_file.sh mode=755

# ydb_config_backup is passed via extra vars, generated as "date '+%Y-%m-%d_%H-%M-%S'"
- name: Backup the existing configuration files
  command: "{{ ydb_dir }}/home/backup_config.sh {{ ydb_config_backup }}"
  become: true
  become_user: ydb
  when: ydb_config_backup is defined

- name: Copy the TLS ca.crt
  copy: src={{ ydb_tls_dir }}/ca.crt dest={{ ydb_dir }}/certs/ca.crt

- name: Public copy of ca.crt
  copy: src={{ ydb_tls_dir }}/ca.crt dest={{ ydb_dir }}/cfg/ca.crt

- name: Check if long or short hostname is used for TLS directory
  local_action:
    module: ansible.builtin.stat
    path: {{ ydb_tls_dir }}/{{ inventory_hostname_short }}/node.crt
    register: v_node_crt

- name: Copy TLS files (short hostname used)
  when: v_node_crt is defined and v_node_crt.stat.isreg is defined and v_node_crt.stat.isreg
  block:
    - name: Copy the TLS node.crt (short hostname used)
      copy: src={{ ydb_tls_dir }}/{{ inventory_hostname_short }}/node.crt dest={{ ydb_dir }}/certs/node.crt
    - name: Copy the TLS node.key (short hostname used)
      copy: src={{ ydb_tls_dir }}/{{ inventory_hostname_short }}/node.key dest={{ ydb_dir }}/certs/node.key
    - name: Copy the TLS web.pem (short hostname used)
      copy: src={{ ydb_tls_dir }}/{{ inventory_hostname_short }}/web.pem dest={{ ydb_dir }}/certs/web.pem

- name: Copy TLS files (full hostname used)
  when: v_node_crt is not defined or v_node_crt.stat.isreg is not defined or v_node_crt.stat.isreg == False
  block:
    - name: Copy the TLS node.crt (full hostname used)
      copy: src={{ ydb_tls_dir }}/{{ inventory_hostname }}/node.crt dest={{ ydb_dir }}/certs/node.crt
    - name: Copy the TLS node.key (full hostname used)
      copy: src={{ ydb_tls_dir }}/{{ inventory_hostname }}/node.key dest={{ ydb_dir }}/certs/node.key
    - name: Copy the TLS web.pem (full hostname used)
      copy: src={{ ydb_tls_dir }}/{{ inventory_hostname }}/web.pem dest={{ ydb_dir }}/certs/web.pem

- name: Copy cluster configuration file
  copy: src={{ ydb_config }} dest={{ ydb_dir }}/cfg/ydbd-config.yaml
  when: ydb_config is defined

- name: Build static node configuration file
  command: "{{ ydb_dir }}/home/update_config_file.sh ydbd-config.yaml ydbd-static.yaml STORAGE {{ ydb_cores_static }}"
  when: ydb_config is defined and ydb_cores_static is defined

- name: Build dynamic node configuration file
  command: "{{ ydb_dir }}/home/update_config_file.sh ydbd-config.yaml ydbd-dynamic.yaml COMPUTE {{ ydb_cores_dynamic }}"
  when: ydb_config is defined and ydb_cores_dynamic is defined
